import styles from "./styles.module.css";
import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={styles.body}>
        <div className={styles.container}>
          <header>
            <nav className={styles.navbar}>
              <Link className={styles.navButton} href="/">Home</Link>
              <Link className={styles.navButton} href="/sobre">Sobre</Link>
              <Link className={styles.navButton} href="/projetos">Projetos</Link>
              <Link className={styles.navButton} href="/contato">Contato</Link>
            </nav>
          </header>

          <main>{children}</main>

          <footer className={styles.footer}>© 2025 - Meu Site - Made by Hércules</footer>
        </div>
      </body>
    </html>
  );
}
