export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang="pt-br">
      <div>
      <header>
        <nav>
          <ul>
          <li><a href="/">Home</a></li>
            <li><a href="/sobre">Sobre</a></li>
            <li><a href="/projetos">Projetos</a></li>
            <li><a href="/contato">Contato</a></li>
          </ul>
        </nav>
      </header>
      <footer>© 2025 - Meu Site - Made Hércules</footer>

      
    </div>
      <body>{children}</body>
      
    </html>
  )
}

